"""INTERNAL layer — browser transport and client runtime integration."""

from __future__ import annotations

from bretzel.runtime.envelope import (
    Envelope,
    Patch,
    build_envelope,
    build_patch,
    default_endpoints,
    parse_client_payload,
    serialize_envelope,
    serialize_patch,
)
from bretzel.runtime.protocol import (
    BZ_ATTR_PREFIX,
    BZ_CLASS_PREFIX,
    BZ_DATA_PREFIX,
    BZ_EFFECT_PREFIX,
    BZ_FOR_PREFIX,
    BZ_ID_ATTR,
    BZ_IF_PREFIX,
    BZ_INIT_PREFIX,
    BZ_MODEL_PREFIX,
    BZ_ON_PREFIX,
    BZ_REF_PREFIX,
    BZ_SHOW_PREFIX,
    BZ_STATE_ATTR,
    BZ_TELEPORT_PREFIX,
    BZ_TEXT_PREFIX,
    DATA_BZ_SIG,
    DATA_BZ_TS,
    DATA_SUBSCRIBE_STATE,
    DATA_SUBSCRIBE_URL,
    ENVELOPE_TAG_NAME,
    HEADER_BZ_SIG,
    HEADER_BZ_TS,
    HEADER_CSRF,
    HEADER_PAGE_ID,
    HEADER_PROTOCOL,
    PATCH_TAG_NAME,
    PROTOCOL_VERSION,
    PUBLIC_ASSET_ROUTES,
    ROUTE_ACTION,
    ROUTE_ICONS,
    ROUTE_PREFIX,
    ROUTE_REFETCH,
    ROUTE_RUNTIME_JS,
    ROUTE_SSE,
    ROUTE_STYLE_CSS,
    ROUTE_THEME_CSS,
    ROUTE_VENDOR,
    SERVERSYNC_KEY,
    SINK_ELEMENT_ID,
    SSE_EVENT_STATE_DIRTY,
    WIRE_ID_SEP,
    is_public_asset_path,
    outlet_id_for,
)
from bretzel.runtime.verbs import (
    copy,
    fullscreen,
    print_page,
    share,
    vibrate,
)
from bretzel.runtime.version import (
    check_compat,
    check_protocol_compat,
    parse_major,
)

__all__ = [
    "copy",
    "fullscreen",
    "print_page",
    "share",
    "vibrate",
    # Protocol constants
    "PROTOCOL_VERSION",
    "BZ_ID_ATTR",
    "BZ_STATE_ATTR",
    "BZ_ON_PREFIX",
    "BZ_MODEL_PREFIX",
    "BZ_ATTR_PREFIX",
    "BZ_CLASS_PREFIX",
    "BZ_TEXT_PREFIX",
    "BZ_SHOW_PREFIX",
    "BZ_IF_PREFIX",
    "BZ_FOR_PREFIX",
    "BZ_DATA_PREFIX",
    "BZ_INIT_PREFIX",
    "BZ_EFFECT_PREFIX",
    "BZ_REF_PREFIX",
    "BZ_TELEPORT_PREFIX",
    "DATA_BZ_SIG",
    "DATA_BZ_TS",
    "HEADER_PROTOCOL",
    "HEADER_BZ_SIG",
    "HEADER_BZ_TS",
    "HEADER_PAGE_ID",
    "HEADER_CSRF",
    "PUBLIC_ASSET_ROUTES",
    "is_public_asset_path",
    "ROUTE_PREFIX",
    "ROUTE_RUNTIME_JS",
    "ROUTE_THEME_CSS",
    "ROUTE_STYLE_CSS",
    "ROUTE_ICONS",
    "ROUTE_VENDOR",
    "ROUTE_ACTION",
    "ROUTE_SSE",
    "ROUTE_REFETCH",
    "SSE_EVENT_STATE_DIRTY",
    "DATA_SUBSCRIBE_STATE",
    "DATA_SUBSCRIBE_URL",
    "SERVERSYNC_KEY",
    "WIRE_ID_SEP",
    "ENVELOPE_TAG_NAME",
    "PATCH_TAG_NAME",
    "SINK_ELEMENT_ID",
    "outlet_id_for",
    # Version helpers
    "check_compat",
    "check_protocol_compat",
    "parse_major",
    # Envelope helpers
    "Envelope",
    "Patch",
    "default_endpoints",
    "build_envelope",
    "build_patch",
    "serialize_envelope",
    "serialize_patch",
    "parse_client_payload",
]
