"""Framework-served static assets — runtime.js, theme.css.

Three things end up under ``/_bretzel/``:

- ``runtime.js``: the shipped JS artefact. Read once at startup.
  Two files, one URL path: dev mode serves the **readable** bundle,
  production serves ``runtime.min.js``, its reduced form. Cf.
  :func:`_runtime_bundle_for`.
- ``theme.css``: generated from :class:`Theme.generate_css` at startup.
- ``style.css``: the Lightning-CSS-compiled output. For phase 1 we
  serve a tiny placeholder when no compile pipeline is wired; once
  ``bretzel build`` runs (phase 3), this serves the real bundle.

Cache strategy:

- ``dev=True`` → ``Cache-Control: no-store`` everywhere. We
  iterate fast on runtime.js and theme.css, the browser MUST refetch
  on every reload or it pins a stale bundle for 1 year.
- ``dev=False`` (prod) → ``immutable`` + ``max-age=1y``. The bundle
  is content-stable per release; cache-busting via the ``?h=<hash>``
  query string the shell injects.

The route registrar gets called once at ``Bretzel`` startup and adds
the three GET routes to the underlying FastAPI instance.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from fastapi import HTTPException, Request
from starlette.responses import FileResponse, Response

from bretzel.render import (
    ROUTE_VENDOR,
    cached_name,
    downloadable_assets,
    icon_payload,
    vendored_is_available,
    vendored_local_path,
)
from bretzel.runtime.protocol import (
    ROUTE_FAVICON,
    ROUTE_ICONS,
    ROUTE_RUNTIME_JS,
    ROUTE_STYLE_CSS,
    ROUTE_THEME_CSS,
    ROUTE_TOUCH_ICON,
)

if TYPE_CHECKING:
    from fastapi import FastAPI


_IMMUTABLE_CACHE = "public, max-age=31536000, immutable"
_NO_CACHE = "no-store"

#: The mark, shipped with the package. Two files, two jobs: the SVG is
#: the tab icon and follows ``prefers-color-scheme``; the PNG exists
#: because iOS does not read the SVG for its home screen, and does not
#: handle transparency — hence its white background.
#:
#: ⚠️ They are served from the INSTALLED PACKAGE, not from the
#: repository: the path derives from this module. A wheel built without
#: them would return 404 on every page's icon, with not a single server
#: error — which is why
#: ``tests/consistency/test_a_page_always_declares_its_icon.py`` checks
#: their presence on disk rather than assuming it.
_MARK_DIR = Path(__file__).resolve().parents[2] / "static"
_FAVICON_FILE = _MARK_DIR / "favicon.svg"
_TOUCH_ICON_FILE = _MARK_DIR / "apple-touch-icon.png"


def _runtime_bundle_for(runtime_js_path: Path, *, dev: bool) -> Path:
    """The file to serve: readable in dev, reduced in production.

    The readable bundle carries 143 KB of comments — prose written for
    whoever is debugging, which has no business in a visitor's browser.
    Its reduced form weighs 26 KB gzipped against 90 (measured on
    2026-08-27) and is generated by the same
    ``python -m bretzel.runtime._build``.

    **The fallback is explicit, never silent.** A cloned repository whose
    build has not been replayed has no ``runtime.min.js``; refusing to
    start would be brutal, serving the other file without saying so would
    let a production twice too heavy go unnoticed forever. So we serve
    the readable one **and we say so**.
    """
    if dev:
        return runtime_js_path
    minified = runtime_js_path.with_name("runtime.min.js")
    if minified.is_file():
        return minified
    print(
        f"[bretzel] {minified.name} absent — la prod sert le bundle lisible "
        f"({runtime_js_path.stat().st_size // 1024} Ko au lieu de ~95). "
        "Lancer ``python -m bretzel.runtime._build``."
    )
    return runtime_js_path


def register_static_routes(
    fastapi: FastAPI,
    *,
    runtime_js_path: Path,
    theme_css: str,
    style_css: str = "",
    # Assets / cache axis. It was called ``debug`` — a name that
    # suggested verbosity governed the headers.
    dev: bool = False,
) -> None:
    """Wire the framework asset routes into ``fastapi``.

    The CSS payloads are passed in as strings rather than file paths
    so the caller (lifecycle.py) can hold them in memory and avoid
    a filesystem read per request.
    """
    if not runtime_js_path.is_file():
        raise FileNotFoundError(
            f"Cannot find runtime.js at {runtime_js_path}. Build it via "
            "``python -m bretzel.runtime._build``."
        )

    cache_header = _NO_CACHE if dev else _IMMUTABLE_CACHE
    bundle_path = _runtime_bundle_for(runtime_js_path, dev=dev)

    @fastapi.get(ROUTE_RUNTIME_JS, include_in_schema=False)
    async def _serve_runtime_js() -> FileResponse:
        return FileResponse(
            bundle_path,
            media_type="application/javascript",
            headers={"Cache-Control": cache_header},
        )

    @fastapi.get(f"{ROUTE_VENDOR}/{{filename}}", include_in_schema=False)
    async def _serve_vendored(filename: str) -> FileResponse:
        """The third-party scripts vendored into ``.bretzel/vendor/``.

        ``filename`` is matched against the table of the three known
        assets, and never joined to the path as-is: a route that builds a
        path from the URL serves the whole disk to whoever writes
        ``../``.

        ⚠️ The comparison is on :func:`cached_name`, **the fingerprinted
        name**, because that is the one ``route_for`` puts in the
        ``<script>``. Comparing against the upstream ``filename``
        delivered three 404s on 2026-08-27: the app lost htmx and iconify
        at once, so its icons and its transport, with not a single server
        error — just three log lines that had to be read.
        """
        for asset in downloadable_assets():
            if cached_name(asset) == filename and vendored_is_available(asset):
                return FileResponse(
                    vendored_local_path(asset),
                    media_type="application/javascript",
                    headers={"Cache-Control": cache_header},
                )
        raise HTTPException(status_code=404)

    @fastapi.get(f"{ROUTE_ICONS}/{{icon_path:path}}", include_in_schema=False)
    async def _serve_icons(icon_path: str, request: Request) -> Response:
        """The icon DATA, relayed and cached.

        The iconify web component queries three third-party hosts for its
        glyphs. This route stands in front: the first request goes out
        once from the SERVER, the next ones come from the project cache,
        and the visitor's browser never talks to Iconify.

        ⚠️ **We RELAY, we do not model.** The body is returned as Iconify
        wrote it, whatever the requested endpoint. Modelling its protocol
        would mean tracking each of its endpoints (collections, last
        modified, search) and repaying the debt on every upstream
        change.

        A 404 when nothing answers: the component then falls back on its
        own hosts, that is to say the behaviour before this route. Never
        do worse than doing nothing.
        """
        query = request.url.query
        wanted = f"/{icon_path}" + (f"?{query}" if query else "")
        body = icon_payload(wanted)
        if body is None:
            raise HTTPException(status_code=404)
        return Response(
            content=body,
            media_type="application/json",
            headers={"Cache-Control": cache_header},
        )

    @fastapi.get(ROUTE_FAVICON, include_in_schema=False)
    async def _serve_favicon() -> FileResponse:
        """The framework's mark, as SVG.

        Mounted EVEN when the app sets its own ``favicon=``: a
        conditional asset route would make the public/private
        classification depend on the config, and ``PUBLIC_ASSET_ROUTES``
        is precisely what an auth guard reads without knowing how the app
        is configured.
        """
        return FileResponse(
            _FAVICON_FILE,
            media_type="image/svg+xml",
            headers={"Cache-Control": cache_header},
        )

    @fastapi.get(ROUTE_TOUCH_ICON, include_in_schema=False)
    async def _serve_touch_icon() -> FileResponse:
        return FileResponse(
            _TOUCH_ICON_FILE,
            media_type="image/png",
            headers={"Cache-Control": cache_header},
        )

    @fastapi.get(ROUTE_THEME_CSS, include_in_schema=False)
    async def _serve_theme_css() -> Response:
        return Response(
            content=theme_css,
            media_type="text/css",
            headers={"Cache-Control": cache_header},
        )

    @fastapi.get(ROUTE_STYLE_CSS, include_in_schema=False)
    async def _serve_style_css() -> Response:
        return Response(
            content=style_css or _EMPTY_STYLE_CSS,
            media_type="text/css",
            headers={"Cache-Control": cache_header},
        )


_EMPTY_STYLE_CSS = (
    "/* Placeholder. Run ``bretzel build`` (or wire Lightning CSS at "
    "startup) to compile your Tailwind utilities into this file. */\n"
)
