"""Immutable virtual-DOM nodes.

Components return ``Node`` trees, never strings. Serialization to HTML lives
in ``serialize.py`` and is the only sanctioned path from a tree to bytes.

All nodes are frozen dataclasses with slots — cheap to allocate, hashable,
comparable, and structurally usable as dict keys or set members.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any


class Node:
    """Marker base class. Concrete subclasses are immutable dataclasses."""

    __slots__ = ()


@dataclass(frozen=True, slots=True)
class Element(Node):
    """A single HTML-ish element with optional attributes and children.

    The ``attrs`` mapping is preserved in insertion order — that order
    becomes the rendered HTML order.
    """

    tag: str
    attrs: Mapping[str, Any] = field(default_factory=dict)
    children: tuple[Node, ...] = ()

    def __hash__(self) -> int:
        # ``Mapping`` is not hashable, so we project it into an ordered
        # tuple of items. Equality remains structural (uses ``__eq__``
        # auto-generated by ``@dataclass``).
        return hash((self.tag, tuple(self.attrs.items()), self.children))


@dataclass(frozen=True, slots=True)
class TextNode(Node):
    """Plain text content. Escaped at serialization time."""

    content: str


@dataclass(frozen=True, slots=True)
class HtmlNode(Node):
    """Pre-rendered raw HTML escape hatch.

    The contents are emitted verbatim — never escaped. This is the only
    legitimate way to inject markup that the framework did not produce. Use
    sparingly ; every occurrence is a candidate XSS sink and should be
    auditable.
    """

    html: str


@dataclass(frozen=True, slots=True)
class FragmentNode(Node):
    """Children grouping with no DOM wrapper.

    Serializes as the concatenation of its children, no surrounding tag.
    Used to return multiple roots from a render where a single ``Node`` is
    expected.
    """

    children: tuple[Node, ...] = ()
