"""Sidebar navigation — data only, no rendering.

Each entry is ``(label, href, icon)``. Sections render top-to-bottom in
the sidebar. As features get mounted, uncomment their entry here AND
add the matching ``app.page(...)`` line to ``app/routes.py``.
"""

NAV = [
    ("OVERVIEW", [
        ("Home", "/", "home"),
        ("App map", "/app-map", "network"),
        ("Theme studio", "/theme-studio", "palette"),
    ]),
    ("PRIMITIVES", [
        ("Text",     "/text",     "type"),
        ("Heading",  "/heading",  "heading-1"),
        ("Icon",     "/icon",     "smile"),
        ("Image",    "/image",    "image"),
        ("Code",     "/code",     "code"),
        ("Markdown", "/markdown", "file-text"),
        ("Html",     "/html",     "file-code"),
        ("Video",    "/video",    "video"),
        ("IFrame",   "/iframe",   "frame"),
        ("Audio",    "/audio",    "volume-2"),
        ("Divider",  "/divider",  "minus"),
        ("Link",     "/link",     "link"),
    ]),
    ("ACTIONS & LAYOUT", [
        ("Button",      "/button",      "mouse-pointer-click"),
        ("Icon button", "/icon-button", "circle-dot"),
        ("Card",        "/card",        "square"),
        ("Carousel",    "/carousel",    "gallery-horizontal"),
        ("Container",   "/container",   "frame"),
        ("Viewport + Pane", "/screen",  "monitor"),
        ("Drag & drop", "/dnd",         "grip-vertical"),
        ("Flex",        "/flex",        "layout"),
        ("Grid",        "/grid",        "grid-3x3"),
        ("Resizable",   "/resizable",   "columns-2"),
        ("VStack / HStack", "/stack",   "rows-3"),
    ]),
    ("FORMS", [
        ("Input",        "/input",        "text-cursor-input"),
        ("Number input", "/number_input", "hash"),
        ("Textarea",     "/textarea",     "align-left"),
        ("Select",   "/select",   "list"),
        ("Combobox", "/combobox", "search"),
        ("Slider",   "/slider",   "sliders-horizontal"),
        ("Calendar",    "/calendar",    "calendar"),
        ("DatePicker",  "/date_picker", "calendar-days"),
        ("DateRangePicker", "/date_range_picker", "calendar-range"),
        ("TimePicker",  "/time_picker", "clock"),
        ("MonthPicker", "/month_picker", "calendar-days"),
        ("WeekPicker",  "/week_picker", "calendar-range"),
        ("ColorPicker", "/color_picker", "palette"),
        ("FileUpload",  "/file_upload", "upload-cloud"),
        ("Signature",   "/signature_pad", "pen-line"),
        ("Checkbox", "/checkbox", "check-square"),
        ("Switch",   "/switch",   "toggle-right"),
        ("Radio",    "/radio",    "circle-dot"),
        ("Toggle group", "/toggle_group", "toggle-left"),
        ("Form",     "/form",     "clipboard-list"),
    ]),
    ("FEEDBACK", [
        ("Alert",        "/alert",        "alert-triangle"),
        ("Banner",       "/banner",       "megaphone"),
        ("EmptyState",   "/empty_state",  "package-open"),
        ("Spinner",      "/spinner",      "loader"),
        ("Progress",     "/progress",     "bar-chart-horizontal"),
        ("Notification", "/notification", "bell"),
    ]),
    ("OVERLAYS", [
        ("Tooltip",  "/tooltip",  "message-square"),
        ("Popover",  "/popover",  "message-circle"),
        ("Dialog",   "/dialog",   "square-stack"),
        ("Drawer",   "/drawer",   "panel-right"),
        ("Dropdown", "/dropdown", "chevron-down"),
    ]),
    ("DATA", [
        ("Badge",     "/badge",     "tag"),
        ("Avatar",    "/avatar",    "user"),
        ("Skeleton",  "/skeleton",  "bone"),
        ("Table",     "/table",     "table"),
        ("Datatable", "/datatable", "table-properties"),
        ("Accordion", "/accordion", "chevrons-up-down"),
        ("Diagram",   "/diagram",   "workflow"),
    ]),
    ("NAVIGATION", [
        ("Pagination", "/pagination", "ellipsis"),
        ("Tabs",       "/tabs",       "folder-tree"),
        ("Stepper",    "/stepper",    "footprints"),
        ("Breadcrumb", "/breadcrumb", "chevron-right"),
        ("Bottom bar", "/bottom-bar", "panel-bottom"),
        ("Sidebar",    "/sidebar",    "panel-left"),
        ("Navbar",     "/navbar",     "panel-top"),
        ("Tree",       "/tree",       "list-tree"),
    ]),
    ("DATA-VIZ", [
        ("Sparkline",     "/sparkline",     "activity"),
        ("Bar chart",     "/bar_chart",     "bar-chart-3"),
        ("Line chart",    "/line_chart",    "line-chart"),
        ("Pie chart",     "/pie_chart",     "pie-chart"),
        ("Scatter chart", "/scatter_chart", "scatter-chart"),
    ]),
    ("META", [
        ("Title / MetaTag / Fragment", "/meta", "tags"),
    ]),
    ("TESTING", [
    ]),
]
