"""Mount every feature page under the application shell.

Pure declaration — imports only ``bretzel`` + the features, never the
app instance. Adding a new feature page : import it here and append a
``page(feat.PATH, layout=shell)(feat.page)`` entry to ``PAGES``. The
sidebar entry goes in ``app/nav.py``. ``main`` rakes ``PAGES`` in via
``app.include``.
"""

from bretzel import layout, page

from examples.playground.app.layout import shell as shell_fn

from examples.playground.features import (
    accordion,
    alert,
    audio,
    app_map,
    avatar,
    badge,
    bar_chart,
    banner,
    bottom_bar,
    breadcrumb,
    button,
    calendar,
    combobox,
    card,
    carousel,
    date_picker as _date_picker_feat,
    date_range_picker as _date_range_picker_feat,
    checkbox,
    resizable,
    signature_pad,
    code,
    container,
    screen,
    dialog,
    color_picker as _color_picker_feat,
    divider,
    theme_studio,
    dnd,
    drawer,
    dropdown,
    empty_state,
    file_upload as _file_upload_feat,
    flex,
    form,
    grid,
    heading,
    home,
    html,
    icon,
    iframe,
    image,
    icon_button,
    input,
    line_chart,
    link,
    markdown,
    navbar,
    meta,
    notification,
    number_input,
    pagination,
    pie_chart,
    popover,
    scatter_chart,
    progress,
    radio,
    select,
    sidebar,
    skeleton,
    sparkline,
    slider,
    spinner,
    stack,
    stepper,
    switch,
    datatable,
    table,
    tabs,
    text,
    textarea,
    month_picker,
    time_picker,
    week_picker,
    diagram,
    toggle_group,
    tooltip,
    tree,
    video,
)

# Decorate the layout once — pages reference the wrapped result.
shell = layout(shell_fn)

# Single-page features. Each feature exports ``PATH`` and ``page``.
PAGES = [
    page(home.PATH,   layout=shell)(home.page),
    page(app_map.PATH, layout=shell)(app_map.page),
    page(button.PATH,      layout=shell)(button.page),
    page(icon_button.PATH, layout=shell)(icon_button.page),
    page(carousel.PATH,   layout=shell)(carousel.page),
    page(dnd.PATH,        layout=shell)(dnd.page),
    page(resizable.PATH,  layout=shell)(resizable.page),
    page(signature_pad.PATH, layout=shell)(signature_pad.page),
    page(card.PATH,        layout=shell)(card.page),
    page(container.PATH,   layout=shell)(container.page),
    page(screen.PATH,      layout=shell)(screen.page),
    # WITHOUT ``layout=`` — a ``ui.viewport`` is ``fixed inset-0``, so
    # it would cover the shell. It is the playground's only page that
    # must mount bare, and it is the component's property that requires
    # it.
    page(screen.DEMO_PATH)(screen.full_demo),
    page(flex.PATH,        layout=shell)(flex.page),
    page(grid.PATH,        layout=shell)(grid.page),
    page(stack.PATH,       layout=shell)(stack.page),
    page(input.PATH,       layout=shell)(input.page),
    page(number_input.PATH, layout=shell)(number_input.page),
    page(textarea.PATH,    layout=shell)(textarea.page),
    page(select.PATH,      layout=shell)(select.page),
    page(combobox.PATH,    layout=shell)(combobox.page),
    page(slider.PATH,      layout=shell)(slider.page),
    page(calendar.PATH,    layout=shell)(calendar.page),
    page(_date_picker_feat.PATH, layout=shell)(_date_picker_feat.page),
    page(_date_range_picker_feat.PATH, layout=shell)(_date_range_picker_feat.page),
    page(_file_upload_feat.PATH, layout=shell)(_file_upload_feat.page),
    page(checkbox.PATH,    layout=shell)(checkbox.page),
    page(switch.PATH,      layout=shell)(switch.page),
    page(radio.PATH,       layout=shell)(radio.page),
    page(form.PATH,        layout=shell)(form.page),
    page(alert.PATH,       layout=shell)(alert.page),
    page(spinner.PATH,     layout=shell)(spinner.page),
    page(progress.PATH,    layout=shell)(progress.page),
    page(notification.PATH, layout=shell)(notification.page),
    page(tooltip.PATH,     layout=shell)(tooltip.page),
    page(popover.PATH,     layout=shell)(popover.page),
    page(dialog.PATH,      layout=shell)(dialog.page),
    page(drawer.PATH,      layout=shell)(drawer.page),
    page(dropdown.PATH,    layout=shell)(dropdown.page),
    page(badge.PATH,       layout=shell)(badge.page),
    page(avatar.PATH,      layout=shell)(avatar.page),
    page(skeleton.PATH,    layout=shell)(skeleton.page),
    page(sparkline.PATH,   layout=shell)(sparkline.page),
    page(bar_chart.PATH,   layout=shell)(bar_chart.page),
    page(line_chart.PATH,  layout=shell)(line_chart.page),
    page(pie_chart.PATH,   layout=shell)(pie_chart.page),
    page(scatter_chart.PATH, layout=shell)(scatter_chart.page),
    page(table.PATH,       layout=shell)(table.page),
    page(datatable.PATH,   layout=shell)(datatable.page),
    page(empty_state.PATH, layout=shell)(empty_state.page),
    page(banner.PATH,      layout=shell)(banner.page),
    page(accordion.PATH,   layout=shell)(accordion.page),
    page(pagination.PATH,  layout=shell)(pagination.page),
    page(tabs.PATH,        layout=shell)(tabs.page),
    page(stepper.PATH,     layout=shell)(stepper.page),
    page(breadcrumb.PATH,  layout=shell)(breadcrumb.page),
    page(bottom_bar.PATH,  layout=shell)(bottom_bar.page),
    page(sidebar.PATH,     layout=shell)(sidebar.page),
    page(navbar.PATH,      layout=shell)(navbar.page),
    page(tree.PATH,        layout=shell)(tree.page),
    page(diagram.PATH,     layout=shell)(diagram.page),
    page(time_picker.PATH, layout=shell)(time_picker.page),
    page(month_picker.PATH, layout=shell)(month_picker.page),
    page(week_picker.PATH, layout=shell)(week_picker.page),
    page(text.PATH,    layout=shell)(text.page),
    page(heading.PATH, layout=shell)(heading.page),
    page(html.PATH,    layout=shell)(html.page),
    page(icon.PATH,    layout=shell)(icon.page),
    page(image.PATH,   layout=shell)(image.page),
    page(_color_picker_feat.PATH, layout=shell)(_color_picker_feat.page),
    page(divider.PATH, layout=shell)(divider.page),
    page(theme_studio.PATH, layout=shell)(theme_studio.page),
    page(link.PATH,    layout=shell)(link.page),
    page(code.PATH,    layout=shell)(code.page),
    page(markdown.PATH, layout=shell)(markdown.page),
    page(video.PATH,   layout=shell)(video.page),
    page(iframe.PATH,  layout=shell)(iframe.page),
    page(audio.PATH,   layout=shell)(audio.page),
    page(meta.PATH,    layout=shell)(meta.page),
    # ⚠️ A ``@download`` is NOT a page: it takes neither shell nor
    # layout, and the render pipeline does not touch it. It is mounted by
    # passing the MARKED function as it is — it is ``include`` that reads
    # ``_bz_download`` and sets the route.
    meta.fruits_csv,
    page(toggle_group.PATH, layout=shell)(toggle_group.page),
]
